fix color item height issue + refactoring
actum/styleguide pull request #7
Opened 2017-02-16 13:28 UTC by ronaldruzicka

I just fixed height issue, for `.sg-color` item and refactored `.kss_example--color` row to be like bootstrap container

2017-02-21 10:57 UTC, vbulant requested changes

2017-02-21 10:57 UTC, vbulant commented on src/styles/main.scss
> +            @media (min-width: 992px) {
There already is `$screen-md-min: 1024px;` on the top of the file so I’d try to reuse that var instead in order to keep the number of breakpoints as small as possible.

Then I’d add other breakpoints (576, 768, 1200) as variables as well so it’s more transparent which ones should be used.

2017-02-21 10:57 UTC, vbulant commented on src/styles/main.scss
> +                max-width: 100%;
Duplicate of the max-width in 576px mq.

2017-02-21 10:57 UTC, vbulant commented on src/styles/main.scss
> +                max-width: 100%;
Duplicate of the max-width in 576px mq.

2017-02-21 10:57 UTC, vbulant commented on src/styles/main.scss
> +                max-width: 100%;
Duplicate of the max-width in 576px mq.

2017-02-21 10:57 UTC, vbulant commented on src/styles/main.scss
> +            padding-left: 15px;
Consider adding $gutter: 30px and reusing it like ($gutter / 2) like in bootstrap so we can reuse it.
I know, it’s like recreating bootstrap less/scss logic again but better that nothing at the moment.

2017-02-23 08:58 UTC, janpanschab approved these changes

2017-02-23 10:47 UTC, merged